postgres-slave:
  image: "chatlamin/postgrespro-1c"
  ports:
    - 5433:5432
  links:
    - postgres-master
  environment:
    REPLICATION_ROLE: slave
    POSTGRES_MASTER_SERVICE_HOST: postgres-master

postgres-master:
  image: "chatlamin/postgrespro-1c"
  ports:
    - 5432:5432
